# Generated by Django 5.0.11 on 2026-02-26 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name_plural': 'ideas'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
