# Generated by Django 5.0.11 on 2026-02-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0002_alter_ideas_options_alter_vote_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_count',
        ),
    ]
